name: Signin
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  signin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run signin script
        env:
          BOHE_ACCOUNTS: ${{ secrets.BOHE_ACCOUNTS }}
        run: poetry run python main.py
